import requests
from webapp.config import STAGE_JIRA_URL, STAGE_JIRA_API_KEY

"""GET API-запрос задач Jira"""
def get_issue():
    url = f'{STAGE_JIRA_URL}/rest/api/2/search'
    headers = {
    "Authorization": f'Bearer {STAGE_JIRA_API_KEY}'
    }
    params = {
        "jql": "project = ATL AND issuetype = Epic AND status = Готово AND key = ATL-1322", # Cтрока запроса JQL
        "startAt": "", # Индекс первого возвратного выпуска (на основе 0)
        "maxResults": "", # Максимальное количество возвращаемых выпусков (по умолчанию 50).
        "validateQuery": "true", # Cледует ли проверять JQL-запрос
        "fields": "summary,customfield_12203", # Список полей, возвращаемых для каждой задачи (*all, customfield_12203, ...)
        "expand": "" #Список параметров, разделенных запятыми, которые необходимо развернуть.
    }
    response = requests.get(url,headers=headers, params=params)
    if response.ok:
        data = response.json()
        return data
    else:
        print('Ошибка: Ошибка при подключении к Jira', response)

print(get_issue())
"""
{
    'expand': 'names,schema',
    'startAt': 0,
    'maxResults': 50,
    'total': 1,
    'issues': [{
        'expand': 'operations,versionedRepresentations,editmeta,changelog,renderedFields',
        'id': '190639',
        'self': 'https://stage-jira.',
        'key': 'ATL-1322',
        'fields': {
            'summary': 'Поддержка продуктов в проекте '
        }
    }]
}
"""

"""POST API-запрос задач Jira"""
def post_issue():
    url = f'{STAGE_JIRA_URL}/rest/api/2/search'
    headers = {
    "Authorization": f'Bearer {STAGE_JIRA_API_KEY}'
    }
    body = {
            "jql": "key = ATL-1322",
            "startAt": 0,
            "maxResults": 15,
            "fields": [
                "summary",
                "status",
                "assignee",
                "customfield_12203"
            ]
    }
    response = requests.post(url,headers=headers, json=body)
    if response.ok:
        data = response.json()
        return data
    else:
        print('Ошибка: Ошибка при подключении к Jira', response)

#print(post_issue())

"""
{
    'expand': 'names,schema',
    'startAt': 0,
    'maxResults': 15,
    'total': 1,
    'issues': [{
        'expand': 'operations,versionedRepresentations,editmeta,changelog,renderedFields',
        'id': '190639',
        'self': 'https://stage-jira.',
        'key': 'ATL-1322',
        'fields': {
            'summary': 'Поддержка продуктов в проекте',
            'assignee': {
                'self': 'https://stage-jira.',
                'name': 'azhitnikova',
                'key': 'JIRAUSER34106',
                'avatarUrls': {
                    '48x48': 'https://stage-jira',
                    '24x24': 'https://stage-jira',
                    '16x16': 'https://stage-jira',
                    '32x32': 'https://stage-jira'
                },
                'displayName': 'Анна ******',
                'active': True,
                'timeZone': 'Europe/Moscow'
            },
            'status': {
                'self': 'https://stage-jira',
                'description': 'This was auto-generated by Jira Service Desk during workflow import',
                'iconUrl': 'https://stage-jira',
                'name': 'Готово',
                'id': '11512',
                'statusCategory': {
                    'self': 'https://stage-jira',
                    'id': 3,
                    'key': 'done',
                    'colorName': 'success',
                    'name': 'Выполнено'
                }
            }
        }
    }]
}
"""