"""added field_status_del to fields

Revision ID: e8592efaff6f
Revises: b25b60f61545
Create Date: 2023-06-25 11:53:26.925458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8592efaff6f'
down_revision = 'b25b60f61545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('field_status_del', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fields', 'field_status_del')
    # ### end Alembic commands ###
